<?xml version="1.0"?>
<robot name="minicar_diff" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Launch arguments -->
  <xacro:arg name="robot_ns" default="sim_robot"/>

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <!-- Robot body dimensions (meters) -->
  <xacro:property name="body_length" value="0.22"/>
  <xacro:property name="body_width" value="0.16"/>
  <xacro:property name="body_height" value="0.065"/>  <!-- 10cm total - 3.5cm wheel radius -->
  
  <!-- Wheel dimensions -->
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheel_separation_width" value="0.195"/>
  <xacro:property name="wheel_separation_length" value="0.115"/>
  
  <!-- Caster wheel dimensions -->
  <xacro:property name="caster_radius" value="0.015"/>
  
  <!-- LiDAR dimensions (55.6x55.6x41.3mm) -->
  <xacro:property name="lidar_radius" value="0.0278"/>
  <xacro:property name="lidar_height" value="0.0413"/>

  <!-- Materials -->
  <material name="white">
    <color rgba="0.8 0.8 0.8 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  
  <material name="blue">
    <color rgba="0.0 0.0 1.0 1.0"/>
  </material>

  <!-- Base footprint (contact point with ground) -->
  <link name="base_footprint">
    <visual>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </visual>
  </link>

  <!-- Base link (robot center) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0053" ixy="0.0" ixz="0.0" iyy="0.0107" iyz="0.0" izz="0.0147"/>
    </inertial>
  </link>

  <!-- Base footprint to base link -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Macro for drive wheels -->
  <xacro:macro name="drive_wheel" params="prefix x y flip">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.000184" ixy="0.0" ixz="0.0" iyy="0.000306" iyz="0.0" izz="0.000184"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y * flip} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Drive wheels (rear) -->
  <xacro:drive_wheel prefix="left_rear" x="${-wheel_separation_length/2}" y="${wheel_separation_width/2}" flip="1"/>
  <xacro:drive_wheel prefix="right_rear" x="${-wheel_separation_length/2}" y="${wheel_separation_width/2}" flip="-1"/>

  <!-- Front drive wheels -->
  <xacro:drive_wheel prefix="left_front" x="${wheel_separation_length/2}" y="${wheel_separation_width/2}" flip="1"/>
  <xacro:drive_wheel prefix="right_front" x="${wheel_separation_length/2}" y="${wheel_separation_width/2}" flip="-1"/>

  <!-- LiDAR -->
  <link name="laser">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0 0 ${body_height/2 + lidar_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo Plugins -->

  <!-- ros2_control hardware interface -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    
    <joint name="left_front_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-20.0</param>
        <param name="max">20.0</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    
    <joint name="right_front_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-20.0</param>
        <param name="max">20.0</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    
    <joint name="left_rear_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-20.0</param>
        <param name="max">20.0</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    
    <joint name="right_rear_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-20.0</param>
        <param name="max">20.0</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
  </ros2_control>

  <!-- Gazebo + ros2_control bridge -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <robot_sim_type>gazebo_ros2_control/GazeboSystem</robot_sim_type>
      <parameters>$(find minicar_simulation)/description/config/minicar_diff_controller.yaml</parameters>
      <ros>
        <namespace>/$(arg robot_ns)</namespace>
      </ros>
    </plugin>
  </gazebo>

  <!-- LiDAR sensor plugin -->
  <gazebo reference="laser">
    <material>Gazebo/Blue</material>
    <sensor name="laser" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0.0</min_angle>
            <max_angle>6.2831854820251465</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.15</min>
          <max>8.0</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.03</stddev>
        </noise>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/$(arg robot_ns)</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Gazebo materials -->
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="left_rear_wheel">
    <material>Gazebo/DarkGrey</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
  </gazebo>

  <gazebo reference="right_rear_wheel">
    <material>Gazebo/DarkGrey</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
  </gazebo>

  <gazebo reference="left_front_wheel">
    <material>Gazebo/DarkGrey</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
  </gazebo>

  <gazebo reference="right_front_wheel">
    <material>Gazebo/DarkGrey</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
  </gazebo>

</robot>